name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: cmake -S src -B build -G "Ninja Multi-Config"

      - name: Build Release
        run: cmake --build build --config Release

      - name: Build Debug
        run: cmake --build build --config Debug

      - name: Package Release
        run: 7z a OpenSteamTool-Release.zip ".\build\Release\*" -mx5

      - name: Package Debug
        run: 7z a OpenSteamTool-Debug.zip ".\build\Debug\*" -mx5

      - uses: actions/upload-artifact@v4
        with:
          name: OpenSteamTool-Release
          path: build/Release/

      - uses: actions/upload-artifact@v4
        with:
          name: OpenSteamTool-Debug
          path: build/Debug/
